create extension if not exists vector;
create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  external_id text not null,
  phone_number text,
  platform text not null default 'whatsapp',
  display_name text,
  opted_in boolean not null default true,
  handoff_requested boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (platform, external_id)
);

create table if not exists public.chat_history (
  id bigint generated by default as identity primary key,
  external_user_id text not null,
  phone_number text,
  platform text not null default 'whatsapp',
  sender text not null check (sender in ('user', 'assistant', 'system')),
  message text not null,
  provider text,
  model text,
  latency_ms integer,
  message_id text,
  created_at timestamptz not null default now(),
  unique (platform, message_id)
);
create index if not exists chat_history_user_created_idx on public.chat_history(platform, external_user_id, created_at desc);

create table if not exists public.knowledge_base (
  id bigint generated by default as identity primary key,
  title text,
  content text not null,
  source text,
  embedding vector(1536),
  approved boolean not null default true,
  version integer not null default 1,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists knowledge_approved_idx on public.knowledge_base(approved);

create table if not exists public.extracted_facts (
  id bigint generated by default as identity primary key,
  fact text not null,
  source text,
  confidence numeric(5,4),
  approved boolean not null default false,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.bot_settings (
  key text primary key,
  value_json jsonb not null,
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.bot_commands (
  id bigint generated by default as identity primary key,
  command text not null unique,
  instruction text not null,
  enabled boolean not null default true,
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.training_revisions (
  id bigint generated by default as identity primary key,
  instructions text not null,
  knowledge text not null,
  changed_by text not null default 'admin',
  created_at timestamptz not null default now()
);

create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text,
  payload jsonb not null,
  status text not null default 'received',
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (provider, event_id)
);

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor text,
  ip_hash text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.match_knowledge(
  query_embedding vector(1536),
  match_threshold float default 0.72,
  match_count int default 6
)
returns table (id bigint, title text, content text, source text, similarity float)
language sql stable
as $$
  select id, title, content, source, 1 - (embedding <=> query_embedding) as similarity
  from public.knowledge_base
  where approved = true and embedding is not null
    and 1 - (embedding <=> query_embedding) >= match_threshold
  order by embedding <=> query_embedding
  limit match_count;
$$;

alter table public.users enable row level security;
alter table public.chat_history enable row level security;
alter table public.knowledge_base enable row level security;
alter table public.extracted_facts enable row level security;
alter table public.bot_settings enable row level security;
alter table public.bot_commands enable row level security;
alter table public.training_revisions enable row level security;
alter table public.webhook_events enable row level security;
alter table public.security_events enable row level security;

-- The server uses the Supabase service-role key. Never expose it in a browser.
-- Add explicit policies only if a browser client needs direct access; the admin UI uses server endpoints.
